services:
  frontend:
    build: .
    container_name: misterticket_frontend
    restart: always
    ports:
      - "3000:3000"  # Expone el puerto 3000 del servidor hacia el 3000 del contenedor
    environment:
      # URL pública de tu backend EC2
      - NEXT_PUBLIC_API_URL=http://3.21.40.91/api